#!/usr/bin/env node
// PreToolUse guard on `git commit`: refuses commits that would stage things this repo should never
// carry, or that would land on a red tree.
//
// Registered with a Bash matcher in settings.json, but DO NOT RELY ON THAT. Hook `if:` filters are
// schema-valid and have been observed not to apply — a guard registered for `git commit` running on
// `git stash show` and then on a plain `cp -R`, denying every Bash call in the session. A hook that can
// brick the shell must not depend on a filter it cannot verify, so the REAL filter is the self-check at
// the top of main().

import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

// Everything here is either a secret, a build product, or a binary that git handles badly. The place
// file entry is the one specific to this project: `.rbxl` files are the MAP, they are large, binary and
// merge-hostile, and the README is explicit that Roblox's cloud place-version history is their backup
// rather than Git.
export const FORBIDDEN = [
  { pattern: /\.rbxlx?$/, reason: 'place files are binary and merge-hostile — the map lives in Roblox cloud history, not Git' },
  { pattern: /^sourcemap\.json$/, reason: 'sourcemap.json is generated by `rojo sourcemap`' },
  { pattern: /^\.luau-defs\//, reason: '.luau-defs/ is a fetched build input, ~1MB, regenerated on demand' },
  { pattern: /^build\//, reason: 'build/ is build output' },
  { pattern: /\.rbxmx?$/, reason: 'model exports are build output' },
  { pattern: /^\.DS_Store$|\/\.DS_Store$/, reason: 'macOS metadata' },
  // `.claude/.gitignore` is the one dotfile here that IS source: it is the file that declares which
  // harness state is runtime. Untracked, a fresh clone has no ignore rules at all and the next commit
  // sweeps up .candidates.jsonl and the heartbeat logs — so the guard would be protecting nothing.
  { pattern: /^\.claude\/\.(?!gitignore$)[\w.-]+$/, reason: 'harness runtime state, not source' }
]

const readStdin = async () => {
  const chunks = []

  for await (const chunk of process.stdin) chunks.push(chunk)

  return Buffer.concat(chunks).toString('utf8')
}

const deny = reason => {
  process.stdout.write(
    `${JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'PreToolUse',
        permissionDecision: 'deny',
        permissionDecisionReason: reason
      }
    })}\n`
  )
  process.exit(0)
}

// Returns [{ status, file }]. The STATUS matters: DELETING a stray place file or a committed sourcemap
// is exactly the right thing to do, and a guard that only looks at filenames blocks the correct action.
// A guard that refuses the correct action teaches people to bypass it.
const stagedEntries = () => {
  try {
    return execFileSync('git', ['diff', '--cached', '--name-status'], { encoding: 'utf8' })
      .split('\n')
      .map(line => line.trim())
      .filter(Boolean)
      .map(line => {
        const [status, ...rest] = line.split(/\s+/)

        return { status: status[0], file: rest[rest.length - 1] }
      })
  } catch {
    return []
  }
}

// Exported so the suite can drive the decision without a git index.
export const judgeStaged = staged => {
  for (const { status, file } of staged) {
    if (status === 'D') continue

    const hit = FORBIDDEN.find(entry => entry.pattern.test(file))

    if (hit) return `Refusing to commit ${file} — ${hit.reason}. Unstage it with: git restore --staged ${file}`
  }

  return null
}

// `git commit` may be anywhere in a chain, so the self-filter looks for it as a command segment rather
// than at the start of the string.
// NEWLINE IS IN THIS LIST BECAUSE IT WAS MISSING, and its absence disabled the guard entirely for a
// very ordinary command shape: any multi-line Bash block whose `git commit` starts its own line. That
// is what a heredoc commit message looks like, and what most scripted commits look like. Found by
// accident while proving a different fix — a probe commit that should have been refused went through.
//
// A guard with a hole this shape is worse than no guard, because every commit that slipped past it
// looked like a commit the guard had approved.
export const isCommit = command => /(^|&&|\|\||;|\||\n)\s*git\s+commit\b/.test(command ?? '')

const main = async () => {
  let payload

  try {
    payload = JSON.parse(await readStdin())
  } catch {
    process.exit(0)
  }

  if (!isCommit(payload?.tool_input?.command ?? '')) process.exit(0)

  const staged = stagedEntries()

  if (staged.length === 0) process.exit(0)

  const forbidden = judgeStaged(staged)

  if (forbidden) deny(forbidden)

  try {
    execFileSync('npm', ['run', '--silent', 'verify:fast'], { encoding: 'utf8', stdio: 'pipe' })

    // ── AND THE DEBUG FLAGS, HERE AND NOT IN verify:fast ────────────────────────
    //
    // `tests/config.test.luau` has always asserted `SoloTesting == false`, and that was believed to be
    // what stopped a debug flag reaching history — the tree goes red, and this guard refuses a red
    // tree. It never did: `verify:fast` does not run `test:unit`, so no assertion in that file has
    // ever been consulted at commit time. An audit found this while reviewing a force-role switch
    // written on the strength of that false guarantee.
    //
    // It runs HERE rather than inside `verify:fast` because `verify-gate.mjs` runs `verify:fast` on
    // every Stop. Putting it there blocks every turn of a Studio session for having testing values
    // set, which is the state a Studio session is SUPPOSED to be in — the guard would make the thing
    // it guards untestable. A commit is the moment the values stop being temporary, so a commit is
    // where the question belongs.
    execFileSync('node', ['.claude/scripts/check-debug.mjs'], { encoding: 'utf8', stdio: 'pipe' })
  } catch (error) {
    const output = `${error.stdout ?? ''}${error.stderr ?? ''}`.trim().split('\n').slice(-12).join('\n')

    deny(`\`npm run verify:fast\` or \`check:debug\` is failing — refusing to commit a red tree.\n\n${output}`)
  }

  process.exit(0)
}

if (process.argv[1]?.endsWith('guard-commit.mjs')) {
  if (process.argv.includes('--self-test')) {
    let failures = 0
    let ran = 0

    const check = (label, actual, expected) => {
      ran += 1
      if (actual === expected) return

      failures += 1
      console.log(`  FAIL  ${label} — expected ${expected}, got ${actual}`)
    }

    // The self-filter is the load-bearing part: without it this guard runs on every Bash command.
    check('a plain commit is recognised', isCommit('git commit -m "x"'), true)
    check('a chained commit is recognised', isCommit('npm run verify && git commit -m "x"'), true)
    check('git stash show is NOT a commit', isCommit('git stash show'), false)
    check('a plain copy is NOT a commit', isCommit('cp -R a b'), false)
    check('grepping for the phrase is NOT a commit', isCommit('grep -rn "git commit" docs/'), false)
    check('git log is NOT a commit', isCommit('git log -5'), false)

    // THE BYPASS. A newline-separated commit is the shape of every heredoc and scripted commit, and it
    // slipped the guard completely until this case existed.
    check('a newline-separated commit is recognised', isCommit('git add -A\ngit commit -m "x"'), true)
    check('a commit after a heredoc terminator is recognised', isCommit('cat <<EOF\nbody\nEOF\ngit commit -F -'), true)
    check('a newline inside a quoted string is still not a commit', isCommit('echo "line\nabout git log"'), false)

    const blocked = staged => judgeStaged(staged) !== null

    // BLOCK
    check('a place file', blocked([{ status: 'A', file: 'ASWANG.rbxl' }]), true)
    check('a generated sourcemap', blocked([{ status: 'M', file: 'sourcemap.json' }]), true)
    check('fetched type definitions', blocked([{ status: 'A', file: '.luau-defs/globalTypes.d.luau' }]), true)
    check('build output', blocked([{ status: 'A', file: 'build/aswang.rbxl' }]), true)
    check('harness runtime state', blocked([{ status: 'M', file: '.claude/.run-ledger.json' }]), true)

    // ALLOW
    check('ordinary Luau source', blocked([{ status: 'M', file: 'src/server/Services/RoundService.luau' }]), false)
    check('a harness script, which IS tracked here', blocked([{ status: 'A', file: '.claude/scripts/check-remotes.mjs' }]), false)
    check('an agent definition', blocked([{ status: 'A', file: '.claude/agents/playtester.md' }]), false)
    check('the tracked analyze baseline', blocked([{ status: 'M', file: 'analyze-baseline.json' }]), false)
    check('a test', blocked([{ status: 'A', file: 'tests/config.test.luau' }]), false)
    // The dotfile that DECLARES the runtime state. Without it tracked, a clone has no ignore rules
    // and everything the rule above blocks gets committed by the next person anyway.
    check('.claude/.gitignore, which IS source', blocked([{ status: 'A', file: '.claude/.gitignore' }]), false)

    // DELETIONS of forbidden files are the CORRECT action and must pass.
    check('deleting a committed place file', blocked([{ status: 'D', file: 'ASWANG.rbxl' }]), false)
    check('deleting a committed sourcemap', blocked([{ status: 'D', file: 'sourcemap.json' }]), false)

    console.log(failures ? `  FAIL  guard-commit: ${ran - failures}/${ran}` : `  PASS  guard-commit: ${ran}/${ran} cases`)
    process.exit(failures ? 1 : 0)
  }

  main()
}
